#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom AnnotationHub query
#' @importFrom BiocGenerics as.list
#' @importFrom bsicons bs_icon
#' @importFrom bslib accordion
#' @importFrom bslib accordion_panel
#' @importFrom bslib css
#' @importFrom bslib layout_columns
#' @importFrom bslib layout_sidebar
#' @importFrom bslib nav_hide
#' @importFrom bslib nav_item
#' @importFrom bslib nav_menu
#' @importFrom bslib nav_panel
#' @importFrom bslib nav_show
#' @importFrom bslib nav_spacer
#' @importFrom bslib page_fillable
#' @importFrom bslib page_navbar
#' @importFrom bslib sidebar
#' @importFrom circlize colorRamp2
#' @importFrom ComplexHeatmap anno_block
#' @importFrom ComplexHeatmap Heatmap
#' @importFrom ComplexHeatmap HeatmapAnnotation
#' @importFrom cowplot plot_grid
#' @importFrom cowplot save_plot
#' @importFrom dplyr across
#' @importFrom dplyr case_when
#' @importFrom dplyr ensym
#' @importFrom dplyr filter
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr where
#' @importFrom DT datatable
#' @importFrom DT formatSignif
#' @importFrom DT renderDT
#' @importFrom edgeR estimateDisp
#' @importFrom edgeR filterByExpr
#' @importFrom edgeR SE2DGEList
#' @importFrom ExperimentHub ExperimentHub
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_colour_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 ylim
#' @importFrom ggpubr as_ggplot
#' @importFrom ggpubr get_legend
#' @importFrom ggrepel geom_text_repel
#' @importFrom grDevices dev.off
#' @importFrom grDevices png
#' @importFrom grid gpar
#' @importFrom grid unit
#' @importFrom htmltools div
#' @importFrom htmltools h4
#' @importFrom htmltools tagList
#' @importFrom limma contrasts.fit
#' @importFrom limma duplicateCorrelation
#' @importFrom limma eBayes
#' @importFrom limma is.fullrank
#' @importFrom limma lmFit
#' @importFrom limma makeContrasts
#' @importFrom limma topTable
#' @importFrom limma voom
#' @importFrom magrittr %>%
#' @importFrom pals alphabet
#' @importFrom pals alphabet2
#' @importFrom pals glasbey
#' @importFrom readr read_delim
#' @importFrom readxl read_excel
#' @importFrom S4Vectors metadata
#' @importFrom scales number_format
#' @importFrom scater runPCA
#' @importFrom shiny addResourcePath
#' @importFrom shiny column
#' @importFrom shiny downloadButton
#' @importFrom shiny downloadHandler
#' @importFrom shiny eventReactive
#' @importFrom shiny fluidRow
#' @importFrom shiny icon
#' @importFrom shiny numericInput
#' @importFrom shiny observeEvent
#' @importFrom shiny radioButtons
#' @importFrom shiny reactive
#' @importFrom shiny renderDataTable
#' @importFrom shiny renderPlot
#' @importFrom shiny renderText
#' @importFrom shiny renderUI
#' @importFrom shiny runApp
#' @importFrom shiny selectInput
#' @importFrom shiny sliderInput
#' @importFrom shiny tabPanel
#' @importFrom shiny tabsetPanel
#' @importFrom shiny tags
#' @importFrom shiny textInput
#' @importFrom shiny textOutput
#' @importFrom shiny uiOutput
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyjs hidden
#' @importFrom shinyjs hide
#' @importFrom shinyjs show
#' @importFrom shinyjs toggle
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets radioGroupButtons
#' @importFrom SingleCellExperiment reducedDim
#' @importFrom standR findNCGs
#' @importFrom standR geomxBatchCorrection
#' @importFrom standR geomxNorm
#' @importFrom standR readGeoMx
#' @importFrom stats model.matrix
#' @importFrom stats setNames
#' @importFrom stringr str_split_1
#' @importFrom SummarizedExperiment assay
#' @importFrom SummarizedExperiment colData
#' @importFrom tibble num
#' @importFrom tibble rownames_to_column
#' @importFrom utils combn
#' @importFrom utils de
#' @importFrom utils globalVariables
#' @importFrom utils write.csv
#' @importFrom utils write.table
#' @importFrom withr with_options
## usethis namespace: end
NULL
